replicaCount: 1
image:
  repository: comments-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8158
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"