events {
    worker_connections 1024;
}

http {
    upstream task_backend {
        server task-service:8000;
    }

    server {
        listen 80;
        
        location /api/v1/ {
            proxy_pass http://task_backend;
            proxy_set_header Host $host;
        }
        
        location /health {
            proxy_pass http://task_backend/health;
        }
        
        location /docs {
            proxy_pass http://task_backend/docs;
        }
    }
}